from __future__ import annotations

IMMUNOID_REGIMENS = {
    "chop": {
        "name": "CHOP",
        "aliases": ["chop"],
        "component_agent_ids": ["cyclophosphamide", "doxorubicin", "vincristine", "prednisone_20"],
        "defaults": {"planned_steroid_duration_days": 5},
    },
    "r_chop": {
        "name": "R-CHOP",
        "aliases": ["r chop", "r-chop", "rchop"],
        "component_agent_ids": ["rituximab", "cyclophosphamide", "doxorubicin", "vincristine", "prednisone_20"],
        "defaults": {"planned_steroid_duration_days": 5},
    },
    "mini_r_chop": {
        "name": "mini-R-CHOP",
        "aliases": ["mini r chop", "mini-r-chop", "minirchop"],
        "component_agent_ids": ["rituximab", "cyclophosphamide", "doxorubicin", "vincristine", "prednisone_20"],
        "defaults": {"planned_steroid_duration_days": 5},
    },
    "pola_r_chp": {
        "name": "pola-R-CHP",
        "aliases": ["pola r chp", "pola-r-chp", "polar chp", "polar-chp", "polar-chop"],
        "component_agent_ids": ["polatuzumab_vedotin", "rituximab", "cyclophosphamide", "doxorubicin", "prednisone_20"],
        "defaults": {"planned_steroid_duration_days": 5},
    },
    "bv_chp": {
        "name": "BV-CHP",
        "aliases": ["bv chp", "bv-chp"],
        "component_agent_ids": ["brentuximab_vedotin", "cyclophosphamide", "doxorubicin", "prednisone_20"],
        "defaults": {"planned_steroid_duration_days": 5},
    },
    "cvp": {
        "name": "CVP",
        "aliases": ["cvp"],
        "component_agent_ids": ["cyclophosphamide", "vincristine", "prednisone_20"],
        "defaults": {"planned_steroid_duration_days": 5},
    },
    "r_cvp": {
        "name": "R-CVP",
        "aliases": ["r cvp", "r-cvp", "rcvp"],
        "component_agent_ids": ["rituximab", "cyclophosphamide", "vincristine", "prednisone_20"],
        "defaults": {"planned_steroid_duration_days": 5},
    },
    "br": {
        "name": "BR",
        "aliases": ["br", "b r", "benda rituximab", "bendamustine rituximab"],
        "component_agent_ids": ["bendamustine", "rituximab"],
        "defaults": {},
    },
    "fcr": {
        "name": "FCR",
        "aliases": ["fcr", "f c r"],
        "component_agent_ids": ["fludarabine", "cyclophosphamide", "rituximab"],
        "defaults": {},
    },
    "epoch": {
        "name": "EPOCH",
        "aliases": ["epoch"],
        "component_agent_ids": ["etoposide", "prednisone_20", "vincristine", "cyclophosphamide", "doxorubicin"],
        "defaults": {"planned_steroid_duration_days": 5},
    },
    "r_epoch": {
        "name": "R-EPOCH",
        "aliases": ["r epoch", "r-epoch", "repoch"],
        "component_agent_ids": ["rituximab", "etoposide", "prednisone_20", "vincristine", "cyclophosphamide", "doxorubicin"],
        "defaults": {"planned_steroid_duration_days": 5},
    },
    "da_r_epoch": {
        "name": "DA-R-EPOCH",
        "aliases": ["da r epoch", "da-r-epoch", "darepoch", "dose adjusted r epoch", "dose-adjusted r epoch"],
        "component_agent_ids": ["rituximab", "etoposide", "prednisone_20", "vincristine", "cyclophosphamide", "doxorubicin"],
        "defaults": {"planned_steroid_duration_days": 5},
    },
    "r_ice": {
        "name": "R-ICE",
        "aliases": ["r ice", "r-ice", "rice"],
        "component_agent_ids": ["rituximab", "ifosfamide", "carboplatin", "etoposide"],
        "defaults": {},
    },
    "r_dhap": {
        "name": "R-DHAP",
        "aliases": ["r dhap", "r-dhap", "rdhap"],
        "component_agent_ids": ["rituximab", "dexamethasone_3", "cytarabine", "cisplatin"],
        "defaults": {"planned_steroid_duration_days": 4},
    },
    "r_gdp": {
        "name": "R-GDP",
        "aliases": ["r gdp", "r-gdp", "rgdp"],
        "component_agent_ids": ["rituximab", "gemcitabine", "dexamethasone_3", "cisplatin"],
        "defaults": {"planned_steroid_duration_days": 4},
    },
    "r_gemox": {
        "name": "R-GemOx",
        "aliases": ["r gemox", "r-gemox", "rgemox", "r gem ox", "r-gem-ox"],
        "component_agent_ids": ["rituximab", "gemcitabine", "oxaliplatin"],
        "defaults": {},
    },
    "avd": {
        "name": "AVD",
        "aliases": ["avd"],
        "component_agent_ids": ["doxorubicin", "vinblastine", "dacarbazine"],
        "defaults": {},
    },
    "aavd": {
        "name": "A+AVD",
        "aliases": ["a avd", "a+avd", "a-avd"],
        "component_agent_ids": ["brentuximab_vedotin", "doxorubicin", "vinblastine", "dacarbazine"],
        "defaults": {},
    },
    "seven_plus_three": {
        "name": "7+3",
        "aliases": ["7+3", "7 plus 3", "seven plus three"],
        "component_agent_ids": ["cytarabine", "daunorubicin"],
        "defaults": {"anticipated_prolonged_profound_neutropenia": True},
    },
    "hidac": {
        "name": "HiDAC",
        "aliases": ["hidac", "hi dac", "high dose cytarabine", "high-dose cytarabine"],
        "component_agent_ids": ["cytarabine"],
        "defaults": {"anticipated_prolonged_profound_neutropenia": True},
    },
    "flag_ida": {
        "name": "FLAG-IDA",
        "aliases": ["flag ida", "flag-ida", "flagida"],
        "component_agent_ids": ["fludarabine", "cytarabine", "idarubicin"],
        "defaults": {"anticipated_prolonged_profound_neutropenia": True},
    },
    "hypercvad_a": {
        "name": "HyperCVAD Part A",
        "aliases": ["hypercvad", "hyper cvad", "hyper-cvad", "hypercvad a", "hypercvad part a"],
        "component_agent_ids": ["cyclophosphamide", "vincristine", "doxorubicin", "dexamethasone_3"],
        "defaults": {"planned_steroid_duration_days": 4, "anticipated_prolonged_profound_neutropenia": True},
    },
    "hypercvad_b": {
        "name": "HyperCVAD Part B",
        "aliases": ["hypercvad b", "hypercvad part b", "hyper-cvad b"],
        "component_agent_ids": ["methotrexate", "cytarabine"],
        "defaults": {"anticipated_prolonged_profound_neutropenia": True},
    },
    "vrd": {
        "name": "VRd",
        "aliases": ["vrd", "v r d", "vrd lite", "vrd-lite"],
        "component_agent_ids": ["bortezomib", "lenalidomide", "dexamethasone_3"],
        "defaults": {"planned_steroid_duration_days": 28},
    },
    "dara_vrd": {
        "name": "Dara-VRd",
        "aliases": ["dara vrd", "dara-vrd", "daravrd", "daratumumab vrd"],
        "component_agent_ids": ["daratumumab", "bortezomib", "lenalidomide", "dexamethasone_3"],
        "defaults": {"planned_steroid_duration_days": 28},
    },
    "krd": {
        "name": "KRd",
        "aliases": ["krd", "k r d"],
        "component_agent_ids": ["carfilzomib", "lenalidomide", "dexamethasone_3"],
        "defaults": {"planned_steroid_duration_days": 28},
    },
    "dara_krd": {
        "name": "Dara-KRd",
        "aliases": ["dara krd", "dara-krd", "darakrd"],
        "component_agent_ids": ["daratumumab", "carfilzomib", "lenalidomide", "dexamethasone_3"],
        "defaults": {"planned_steroid_duration_days": 28},
    },
    "rd": {
        "name": "Rd",
        "aliases": ["rd", "r d", "len dex", "lenalidomide dexamethasone"],
        "component_agent_ids": ["lenalidomide", "dexamethasone_3"],
        "defaults": {"planned_steroid_duration_days": 28},
    },
    "dara_rd": {
        "name": "Dara-Rd",
        "aliases": ["dara rd", "dara-rd", "darard"],
        "component_agent_ids": ["daratumumab", "lenalidomide", "dexamethasone_3"],
        "defaults": {"planned_steroid_duration_days": 28},
    },
    "cybord": {
        "name": "CyBorD",
        "aliases": ["cybord", "cy bord", "cy-bord", "cbd", "cyclophosphamide bortezomib dexamethasone"],
        "component_agent_ids": ["cyclophosphamide", "bortezomib", "dexamethasone_3"],
        "defaults": {"planned_steroid_duration_days": 28},
    },
    "dara_cybord": {
        "name": "Dara-CyBorD",
        "aliases": ["dara cybord", "dara-cybord", "daracybord"],
        "component_agent_ids": ["daratumumab", "cyclophosphamide", "bortezomib", "dexamethasone_3"],
        "defaults": {"planned_steroid_duration_days": 28},
    },
}

