from __future__ import annotations

# Generated from /Users/alvaroayala/Desktop/IDHub/lib/immunoData.ts
# Keeps the API catalog aligned with the full ImmunoID medication list and risk tags.

IMMUNOID_SOURCE_AGENTS = {
    'prednisone_20': {
        "name": 'Prednisone >= 20 mg/day',
        "drug_class": 'Corticosteroid (systemic)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'TB (reactivation)', 'Strongyloides', 'PJP', 'C. difficile'],
        "groups": [],
    },
    'prednisolone_20': {
        "name": 'Prednisolone >= 20 mg/day',
        "drug_class": 'Corticosteroid (systemic)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'TB (reactivation)', 'Strongyloides', 'PJP', 'C. difficile'],
        "groups": [],
    },
    'methylpred_16': {
        "name": 'Methylprednisolone >= 16 mg/day',
        "drug_class": 'Corticosteroid (systemic)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'TB (reactivation)', 'Strongyloides', 'PJP', 'C. difficile'],
        "groups": [],
    },
    'hydrocortisone_80': {
        "name": 'Hydrocortisone >= 80 mg/day',
        "drug_class": 'Corticosteroid (systemic)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'TB (reactivation)', 'Strongyloides', 'PJP', 'C. difficile'],
        "groups": [],
    },
    'dexamethasone_3': {
        "name": 'Dexamethasone >= 3 mg/day',
        "drug_class": 'Corticosteroid (systemic)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'TB (reactivation)', 'Strongyloides', 'PJP', 'C. difficile'],
        "groups": [],
    },
    'budesonide_6': {
        "name": 'Budesonide >= 6 mg/day',
        "drug_class": 'Corticosteroid (mostly local effect)',
        "risk_tags": ['Bacterial (general)', 'C. difficile'],
        "groups": [],
    },
    'cyclophosphamide': {
        "name": 'Cyclophosphamide',
        "drug_class": 'Alkylating agent (Nitrogen mustard)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'ifosfamide': {
        "name": 'Ifosfamide',
        "drug_class": 'Alkylating agent (Nitrogen mustard)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'mechlorethamine': {
        "name": 'Mechlorethamine',
        "drug_class": 'Alkylating agent (Nitrogen mustard)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'chlorambucil': {
        "name": 'Chlorambucil',
        "drug_class": 'Alkylating agent (Nitrogen mustard)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'bendamustine': {
        "name": 'Bendamustine',
        "drug_class": 'Alkylating agent (Nitrogen mustard)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'melphalan': {
        "name": 'Melphalan',
        "drug_class": 'Alkylating agent (Nitrogen mustard)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'carmustine': {
        "name": 'Carmustine',
        "drug_class": 'Alkylating agent (Nitrosourea)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'lomustine': {
        "name": 'Lomustine',
        "drug_class": 'Alkylating agent (Nitrosourea)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'streptozocin': {
        "name": 'Streptozocin',
        "drug_class": 'Alkylating agent (Nitrosourea)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'busulfan': {
        "name": 'Busulfan',
        "drug_class": 'Alkylating agent (Alkyl sulfonate)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'dacarbazine': {
        "name": 'Dacarbazine',
        "drug_class": 'Alkylating agent (Triazine/hydrazine-related)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'procarbazine': {
        "name": 'Procarbazine',
        "drug_class": 'Alkylating agent (Triazine/hydrazine-related)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'temozolomide': {
        "name": 'Temozolomide',
        "drug_class": 'Alkylating agent (Triazine/hydrazine-related)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'altretamine': {
        "name": 'Altretamine',
        "drug_class": 'Alkylating agent (Aziridine/epoxide-related)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'thiotepa': {
        "name": 'Thiotepa',
        "drug_class": 'Alkylating agent (Aziridine/epoxide-related)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'mitomycin_c': {
        "name": 'Mitomycin C',
        "drug_class": 'Alkylating agent (Aziridine/epoxide-related)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'diaziquone': {
        "name": 'Diaziquone',
        "drug_class": 'Alkylating agent (Aziridine/epoxide-related)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'cisplatin': {
        "name": 'Cisplatin',
        "drug_class": 'Alkylating agent (Platinum)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'carboplatin': {
        "name": 'Carboplatin',
        "drug_class": 'Alkylating agent (Platinum)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'oxaliplatin': {
        "name": 'Oxaliplatin',
        "drug_class": 'Alkylating agent (Platinum)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP', 'CMV'],
        "groups": ['cytotoxic_chemo'],
    },
    'vincristine': {
        "name": 'Vincristine',
        "drug_class": 'Cytotoxic chemotherapy (vinca alkaloid)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile'],
        "groups": ['cytotoxic_chemo'],
    },
    'vinblastine': {
        "name": 'Vinblastine',
        "drug_class": 'Cytotoxic chemotherapy (vinca alkaloid)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile'],
        "groups": ['cytotoxic_chemo'],
    },
    'vinorelbine': {
        "name": 'Vinorelbine',
        "drug_class": 'Cytotoxic chemotherapy (vinca alkaloid)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile'],
        "groups": ['cytotoxic_chemo'],
    },
    'doxorubicin': {
        "name": 'Doxorubicin',
        "drug_class": 'Cytotoxic chemotherapy (anthracycline)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'C. difficile'],
        "groups": ['cytotoxic_chemo'],
    },
    'daunorubicin': {
        "name": 'Daunorubicin',
        "drug_class": 'Cytotoxic chemotherapy (anthracycline)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'C. difficile'],
        "groups": ['cytotoxic_chemo'],
    },
    'idarubicin': {
        "name": 'Idarubicin',
        "drug_class": 'Cytotoxic chemotherapy (anthracycline)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'C. difficile'],
        "groups": ['cytotoxic_chemo'],
    },
    'epirubicin': {
        "name": 'Epirubicin',
        "drug_class": 'Cytotoxic chemotherapy (anthracycline)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'C. difficile'],
        "groups": ['cytotoxic_chemo'],
    },
    'etoposide': {
        "name": 'Etoposide',
        "drug_class": 'Cytotoxic chemotherapy (epipodophyllotoxin / topoisomerase II inhibitor)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'C. difficile'],
        "groups": ['cytotoxic_chemo'],
    },
    'teniposide': {
        "name": 'Teniposide',
        "drug_class": 'Cytotoxic chemotherapy (epipodophyllotoxin / topoisomerase II inhibitor)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'C. difficile'],
        "groups": ['cytotoxic_chemo'],
    },
    'methotrexate': {
        "name": 'Methotrexate',
        "drug_class": 'Antimetabolite (immunomodulator)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'PJP'],
        "groups": [],
    },
    'pemetrexed': {
        "name": 'Pemetrexed',
        "drug_class": 'Antimetabolite',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile', 'Invasive mold (Aspergillus)', 'PJP'],
        "groups": ['cytotoxic_chemo'],
    },
    'fluorouracil_5': {
        "name": '5-fluorouracil (5-FU)',
        "drug_class": 'Antimetabolite',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile', 'Invasive mold (Aspergillus)', 'PJP'],
        "groups": ['cytotoxic_chemo'],
    },
    'capecitabine': {
        "name": 'Capecitabine',
        "drug_class": 'Antimetabolite',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile', 'Invasive mold (Aspergillus)', 'PJP'],
        "groups": ['cytotoxic_chemo'],
    },
    'cytarabine': {
        "name": 'Cytarabine',
        "drug_class": 'Antimetabolite',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile', 'Invasive mold (Aspergillus)', 'PJP'],
        "groups": ['cytotoxic_chemo'],
    },
    'gemcitabine': {
        "name": 'Gemcitabine',
        "drug_class": 'Antimetabolite',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile', 'Invasive mold (Aspergillus)', 'PJP'],
        "groups": ['cytotoxic_chemo'],
    },
    'mercaptopurine': {
        "name": 'Mercaptopurine (6-MP)',
        "drug_class": 'Antimetabolite (thiopurine)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'CMV', 'PJP'],
        "groups": [],
    },
    'thioguanine': {
        "name": 'Thioguanine',
        "drug_class": 'Antimetabolite (thiopurine)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'CMV'],
        "groups": [],
    },
    'mycophenolate_mofetil': {
        "name": 'Mycophenolate mofetil (MMF)',
        "drug_class": 'Transplant / immunosuppressive (Antimetabolite)',
        "risk_tags": ['Bacterial (general)', 'CMV', 'PJP', 'VZV/HSV'],
        "groups": ['strongy_context'],
    },
    'azathioprine': {
        "name": 'Azathioprine',
        "drug_class": 'Transplant / immunosuppressive (Antimetabolite (thiopurine))',
        "risk_tags": ['Bacterial (general)', 'CMV', 'PJP', 'VZV/HSV'],
        "groups": ['strongy_context'],
    },
    'tacrolimus': {
        "name": 'Tacrolimus',
        "drug_class": 'Transplant / immunosuppressive (Calcineurin inhibitor)',
        "risk_tags": ['Bacterial (general)', 'CMV', 'PJP', 'Nocardia'],
        "groups": ['strongy_context'],
    },
    'cyclosporine': {
        "name": 'Cyclosporine',
        "drug_class": 'Transplant / immunosuppressive (Calcineurin inhibitor)',
        "risk_tags": ['Bacterial (general)', 'CMV', 'PJP', 'Nocardia'],
        "groups": ['strongy_context'],
    },
    'sirolimus': {
        "name": 'Sirolimus',
        "drug_class": 'Transplant / immunosuppressive (mTOR inhibitor)',
        "risk_tags": ['Bacterial (general)', 'CMV', 'PJP'],
        "groups": ['strongy_context'],
    },
    'everolimus': {
        "name": 'Everolimus',
        "drug_class": 'Transplant / immunosuppressive (mTOR inhibitor)',
        "risk_tags": ['Bacterial (general)', 'CMV', 'PJP'],
        "groups": ['strongy_context'],
    },
    'basiliximab': {
        "name": 'Basiliximab',
        "drug_class": 'Transplant / immunosuppressive (IL-2 receptor antagonist (induction))',
        "risk_tags": ['Bacterial (general)', 'CMV', 'PJP'],
        "groups": ['strongy_context'],
    },
    'belatacept': {
        "name": 'Belatacept',
        "drug_class": 'Transplant / immunosuppressive (Costimulation blocker)',
        "risk_tags": ['Bacterial (general)', 'CMV', 'PJP', 'EBV/PTLD'],
        "groups": ['strongy_context'],
    },
    'antithymocyte_globulin': {
        "name": 'Anti-thymocyte globulin (ATG)',
        "drug_class": 'Transplant / immunosuppressive (Lymphocyte-depleting polyclonal antibody)',
        "risk_tags": ['Bacterial (general)', 'CMV', 'PJP', 'VZV/HSV', 'Invasive mold (Aspergillus)'],
        "groups": ['strongy_context'],
    },
    'infliximab': {
        "name": 'Infliximab',
        "drug_class": 'TNF blocker',
        "risk_tags": ['TB (reactivation)', 'Endemic fungi', 'Listeria', 'VZV/HSV', 'Bacterial (general)'],
        "groups": ['tb_screen', 'cocci_context', 'histo_context'],
    },
    'etanercept': {
        "name": 'Etanercept',
        "drug_class": 'TNF blocker',
        "risk_tags": ['TB (reactivation)', 'Endemic fungi', 'Listeria', 'VZV/HSV', 'Bacterial (general)'],
        "groups": ['tb_screen', 'cocci_context', 'histo_context'],
    },
    'adalimumab': {
        "name": 'Adalimumab',
        "drug_class": 'TNF blocker',
        "risk_tags": ['TB (reactivation)', 'Endemic fungi', 'Listeria', 'VZV/HSV', 'Bacterial (general)'],
        "groups": ['tb_screen', 'cocci_context', 'histo_context'],
    },
    'certolizumab': {
        "name": 'Certolizumab pegol',
        "drug_class": 'TNF blocker',
        "risk_tags": ['TB (reactivation)', 'Endemic fungi', 'Listeria', 'VZV/HSV', 'Bacterial (general)'],
        "groups": ['tb_screen', 'cocci_context', 'histo_context'],
    },
    'golimumab': {
        "name": 'Golimumab',
        "drug_class": 'TNF blocker',
        "risk_tags": ['TB (reactivation)', 'Endemic fungi', 'Listeria', 'VZV/HSV', 'Bacterial (general)'],
        "groups": ['tb_screen', 'cocci_context', 'histo_context'],
    },
    'ibrutinib': {
        "name": 'Ibrutinib',
        "drug_class": 'Targeted therapy (BTK inhibitor)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'acalabrutinib': {
        "name": 'Acalabrutinib',
        "drug_class": 'Targeted therapy (BTK inhibitor)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'zanubrutinib': {
        "name": 'Zanubrutinib',
        "drug_class": 'Targeted therapy (BTK inhibitor)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'pirtobrutinib': {
        "name": 'Pirtobrutinib',
        "drug_class": 'Targeted therapy (BTK inhibitor)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'eculizumab': {
        "name": 'Eculizumab',
        "drug_class": 'Complement inhibitor (C5)',
        "risk_tags": ['Encapsulated bacteria', 'Bacterial (general)'],
        "groups": ['complement_c5'],
    },
    'ravulizumab': {
        "name": 'Ravulizumab',
        "drug_class": 'Complement inhibitor (C5)',
        "risk_tags": ['Encapsulated bacteria', 'Bacterial (general)'],
        "groups": ['complement_c5'],
    },
    'rituximab': {
        "name": 'Rituximab',
        "drug_class": 'Monoclonal antibody (anti-CD20)',
        "risk_tags": ['HBV reactivation', 'Encapsulated bacteria', 'VZV/HSV', 'PJP'],
        "groups": [],
    },
    'anakinra': {
        "name": 'Anakinra',
        "drug_class": 'Biologic (IL-1 receptor antagonist)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV'],
        "groups": [],
    },
    'tocilizumab': {
        "name": 'Tocilizumab',
        "drug_class": 'Biologic (IL-6 receptor inhibitor)',
        "risk_tags": ['Bacterial (general)', 'TB (reactivation)', 'VZV/HSV'],
        "groups": [],
    },
    'sarilumab': {
        "name": 'Sarilumab',
        "drug_class": 'Biologic (IL-6 receptor inhibitor)',
        "risk_tags": ['Bacterial (general)', 'TB (reactivation)', 'VZV/HSV'],
        "groups": [],
    },
    'abatacept': {
        "name": 'Abatacept',
        "drug_class": 'Immunomodulator (CTLA-4 Ig)',
        "risk_tags": ['Bacterial (general)', 'TB (reactivation)', 'VZV/HSV'],
        "groups": [],
    },
    'ustekinumab': {
        "name": 'Ustekinumab',
        "drug_class": 'Biologic (IL-12/23 inhibitor)',
        "risk_tags": ['Bacterial (general)', 'TB (reactivation)'],
        "groups": [],
    },
    'guselkumab': {
        "name": 'Guselkumab',
        "drug_class": 'Biologic (IL-23 inhibitor)',
        "risk_tags": ['Bacterial (general)', 'TB (reactivation)'],
        "groups": [],
    },
    'risankizumab': {
        "name": 'Risankizumab',
        "drug_class": 'Biologic (IL-23 inhibitor)',
        "risk_tags": ['Bacterial (general)', 'TB (reactivation)'],
        "groups": [],
    },
    'tildrakizumab': {
        "name": 'Tildrakizumab',
        "drug_class": 'Biologic (IL-23 inhibitor)',
        "risk_tags": ['Bacterial (general)', 'TB (reactivation)'],
        "groups": [],
    },
    'secukinumab': {
        "name": 'Secukinumab',
        "drug_class": 'Biologic (IL-17A inhibitor)',
        "risk_tags": ['Fungal (Candida)', 'Bacterial (general)'],
        "groups": [],
    },
    'ixekizumab': {
        "name": 'Ixekizumab',
        "drug_class": 'Biologic (IL-17A inhibitor)',
        "risk_tags": ['Fungal (Candida)', 'Bacterial (general)'],
        "groups": [],
    },
    'brodalumab': {
        "name": 'Brodalumab',
        "drug_class": 'Biologic (IL-17 receptor inhibitor)',
        "risk_tags": ['Fungal (Candida)', 'Bacterial (general)'],
        "groups": [],
    },
    'bimekizumab': {
        "name": 'Bimekizumab',
        "drug_class": 'Biologic (IL-17A/F inhibitor)',
        "risk_tags": ['Fungal (Candida)', 'Bacterial (general)'],
        "groups": [],
    },
    'vedolizumab': {
        "name": 'Vedolizumab',
        "drug_class": 'Biologic (anti-integrin; gut-selective)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'natalizumab': {
        "name": 'Natalizumab',
        "drug_class": 'Biologic (anti-integrin)',
        "risk_tags": ['JC Virus (PML)', 'VZV/HSV', 'Bacterial (general)'],
        "groups": [],
    },
    'tofacitinib': {
        "name": 'Tofacitinib',
        "drug_class": 'JAK inhibitor',
        "risk_tags": ['VZV/HSV', 'TB (reactivation)', 'Bacterial (general)', 'PJP'],
        "groups": [],
    },
    'baricitinib': {
        "name": 'Baricitinib',
        "drug_class": 'JAK inhibitor',
        "risk_tags": ['VZV/HSV', 'TB (reactivation)', 'Bacterial (general)', 'PJP'],
        "groups": [],
    },
    'upadacitinib': {
        "name": 'Upadacitinib',
        "drug_class": 'JAK inhibitor',
        "risk_tags": ['VZV/HSV', 'TB (reactivation)', 'Bacterial (general)', 'PJP'],
        "groups": [],
    },
    'ruxolitinib': {
        "name": 'Ruxolitinib',
        "drug_class": 'JAK inhibitor',
        "risk_tags": ['VZV/HSV', 'Bacterial (general)', 'TB (reactivation)', 'PJP'],
        "groups": [],
    },
    'deucravacitinib': {
        "name": 'Deucravacitinib',
        "drug_class": 'Immunomodulator (TYK2 inhibitor)',
        "risk_tags": ['VZV/HSV', 'TB (reactivation)', 'Bacterial (general)'],
        "groups": [],
    },
    'apremilast': {
        "name": 'Apremilast',
        "drug_class": 'Immunomodulator (PDE4 inhibitor)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'belimumab': {
        "name": 'Belimumab',
        "drug_class": 'Biologic (anti-BLyS/BAFF)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV'],
        "groups": [],
    },
    'anifrolumab': {
        "name": 'Anifrolumab',
        "drug_class": 'Biologic (type I IFN receptor inhibitor)',
        "risk_tags": ['VZV/HSV', 'Bacterial (general)'],
        "groups": [],
    },
    'emapalumab': {
        "name": 'Emapalumab',
        "drug_class": 'Biologic (anti-IFN-gamma)',
        "risk_tags": ['TB (reactivation)', 'Endemic fungi', 'Bacterial (general)', 'CMV'],
        "groups": [],
    },
    'canakinumab': {
        "name": 'Canakinumab',
        "drug_class": 'Biologic (IL-1beta inhibitor)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV'],
        "groups": [],
    },
    'rilonacept': {
        "name": 'Rilonacept',
        "drug_class": 'Biologic (IL-1 inhibitor)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV'],
        "groups": [],
    },
    'leflunomide': {
        "name": 'Leflunomide',
        "drug_class": 'DMARD (pyrimidine synthesis inhibitor)',
        "risk_tags": ['Bacterial (general)', 'TB (reactivation)', 'VZV/HSV'],
        "groups": [],
    },
    'mirikizumab': {
        "name": 'Mirikizumab',
        "drug_class": 'Biologic (IL-23 inhibitor)',
        "risk_tags": ['Bacterial (general)', 'TB (reactivation)'],
        "groups": [],
    },
    'mepolizumab': {
        "name": 'Mepolizumab',
        "drug_class": 'Biologic (IL-5 pathway inhibitor)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'benralizumab': {
        "name": 'Benralizumab',
        "drug_class": 'Biologic (IL-5 receptor inhibitor)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'avacopan': {
        "name": 'Avacopan',
        "drug_class": 'Targeted therapy (C5a receptor inhibitor)',
        "risk_tags": ['Bacterial (general)', 'Encapsulated bacteria'],
        "groups": [],
    },
    'fingolimod': {
        "name": 'Fingolimod',
        "drug_class": 'Immunomodulator (S1P receptor modulator)',
        "risk_tags": ['VZV/HSV', 'Cryptococcus', 'JC Virus (PML)', 'Bacterial (general)'],
        "groups": [],
    },
    'siponimod': {
        "name": 'Siponimod',
        "drug_class": 'Immunomodulator (S1P receptor modulator)',
        "risk_tags": ['VZV/HSV', 'Cryptococcus', 'JC Virus (PML)', 'Bacterial (general)'],
        "groups": [],
    },
    'ozanimod': {
        "name": 'Ozanimod',
        "drug_class": 'Immunomodulator (S1P receptor modulator)',
        "risk_tags": ['VZV/HSV', 'Cryptococcus', 'Bacterial (general)'],
        "groups": [],
    },
    'ponesimod': {
        "name": 'Ponesimod',
        "drug_class": 'Immunomodulator (S1P receptor modulator)',
        "risk_tags": ['VZV/HSV', 'Cryptococcus', 'Bacterial (general)'],
        "groups": [],
    },
    'etrasimod': {
        "name": 'Etrasimod',
        "drug_class": 'Immunomodulator (S1P receptor modulator)',
        "risk_tags": ['VZV/HSV', 'Bacterial (general)'],
        "groups": [],
    },
    'dimethyl_fumarate': {
        "name": 'Dimethyl fumarate',
        "drug_class": 'Immunomodulator (fumarate)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'JC Virus (PML)'],
        "groups": [],
    },
    'diroximel_fumarate': {
        "name": 'Diroximel fumarate',
        "drug_class": 'Immunomodulator (fumarate)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'JC Virus (PML)'],
        "groups": [],
    },
    'teriflunomide': {
        "name": 'Teriflunomide',
        "drug_class": 'Immunomodulator (DHODH inhibitor)',
        "risk_tags": ['Bacterial (general)', 'TB (reactivation)', 'VZV/HSV'],
        "groups": [],
    },
    'hydroxychloroquine': {
        "name": 'Hydroxychloroquine',
        "drug_class": 'DMARD (immunomodulator)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'ipilimumab': {
        "name": 'Ipilimumab (Yervoy)',
        "drug_class": 'Checkpoint inhibitor (CTLA-4)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'nivolumab': {
        "name": 'Nivolumab (Opdivo)',
        "drug_class": 'Checkpoint inhibitor (PD-1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'pembrolizumab': {
        "name": 'Pembrolizumab (Keytruda)',
        "drug_class": 'Checkpoint inhibitor (PD-1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'cemiplimab': {
        "name": 'Cemiplimab (Libtayo)',
        "drug_class": 'Checkpoint inhibitor (PD-1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'atezolizumab': {
        "name": 'Atezolizumab (Tecentriq)',
        "drug_class": 'Checkpoint inhibitor (PD-L1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'avelumab': {
        "name": 'Avelumab (Bavencio)',
        "drug_class": 'Checkpoint inhibitor (PD-L1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'durvalumab': {
        "name": 'Durvalumab (Imfinzi)',
        "drug_class": 'Checkpoint inhibitor (PD-L1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'dostarlimab': {
        "name": 'Dostarlimab (Jemperli)',
        "drug_class": 'Checkpoint inhibitor (PD-1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'retifanlimab': {
        "name": 'Retifanlimab (Zynyz)',
        "drug_class": 'Checkpoint inhibitor (PD-1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'toripalimab': {
        "name": 'Toripalimab (Loqtorzi)',
        "drug_class": 'Checkpoint inhibitor (PD-1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'tremelimumab': {
        "name": 'Tremelimumab (Imjudo)',
        "drug_class": 'Checkpoint inhibitor (CTLA-4)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'relatlimab': {
        "name": 'Relatlimab (part of Opdualag)',
        "drug_class": 'Checkpoint inhibitor (LAG-3)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'cosibelimab': {
        "name": 'Cosibelimab (Unloxcyt)',
        "drug_class": 'Checkpoint inhibitor (PD-L1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'atezolizumab_hybreza': {
        "name": 'Atezolizumab + hyaluronidase (Tecentriq Hybreza)',
        "drug_class": 'Checkpoint inhibitor (PD-L1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'nivolumab_qvantig': {
        "name": 'Nivolumab + hyaluronidase (Opdivo Qvantig)',
        "drug_class": 'Checkpoint inhibitor (PD-1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'opdualag_combo': {
        "name": 'Nivolumab + relatlimab (Opdualag)',
        "drug_class": 'Checkpoint inhibitor (PD-1)',
        "risk_tags": ['Bacterial (general)', 'C. difficile', 'TB (reactivation)'],
        "groups": [],
    },
    'brexu_cel': {
        "name": 'Brexucabtagene autoleucel (Tecartus)',
        "drug_class": 'Cell therapy (CAR-T / adoptive cellular therapy)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'axi_cel': {
        "name": 'Axicabtagene ciloleucel (Yescarta)',
        "drug_class": 'Cell therapy (CAR-T / adoptive cellular therapy)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'tisa_cel': {
        "name": 'Tisagenlecleucel (Kymriah)',
        "drug_class": 'Cell therapy (CAR-T / adoptive cellular therapy)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'liso_cel': {
        "name": 'Lisocabtagene maraleucel (Breyanzi)',
        "drug_class": 'Cell therapy (CAR-T / adoptive cellular therapy)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'ide_cel': {
        "name": 'Idecabtagene vicleucel (Abecma)',
        "drug_class": 'Cell therapy (CAR-T / adoptive cellular therapy)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'cilta_cel': {
        "name": 'Ciltacabtagene autoleucel (Carvykti)',
        "drug_class": 'Cell therapy (CAR-T / adoptive cellular therapy)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'afami_cel': {
        "name": 'Afamitresgene autoleucel (Tecelra)',
        "drug_class": 'Cell therapy (CAR-T / adoptive cellular therapy)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'lifileucel': {
        "name": 'Lifileucel (Amtagvi)',
        "drug_class": 'Cell therapy (CAR-T / adoptive cellular therapy)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'sipuleucel_t': {
        "name": 'Sipuleucel-T (Provenge)',
        "drug_class": 'Immune-stimulating cytokine / immunotherapy',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'blinatumomab': {
        "name": 'Blinatumomab (Blincyto)',
        "drug_class": 'Bispecific T-cell engager (target CD3 x CD19)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP'],
        "groups": [],
    },
    'glofitamab': {
        "name": 'Glofitamab (Columvi)',
        "drug_class": 'Bispecific T-cell engager (target CD3 x CD20)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP'],
        "groups": [],
    },
    'mosunetuzumab': {
        "name": 'Mosunetuzumab (Lunsumio)',
        "drug_class": 'Bispecific T-cell engager (target CD3 x CD20)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP'],
        "groups": [],
    },
    'epcoritamab': {
        "name": 'Epcoritamab (Epkinly / Tepkinly)',
        "drug_class": 'Bispecific T-cell engager (target CD3 x CD20)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP'],
        "groups": [],
    },
    'teclistamab': {
        "name": 'Teclistamab (Tecvayli)',
        "drug_class": 'Bispecific T-cell engager (target CD3 x BCMA)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP'],
        "groups": [],
    },
    'elranatamab': {
        "name": 'Elranatamab (Elrexfio)',
        "drug_class": 'Bispecific T-cell engager (target CD3 x BCMA)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP'],
        "groups": [],
    },
    'talquetamab': {
        "name": 'Talquetamab (Talvey)',
        "drug_class": 'Bispecific T-cell engager (target CD3 x GPRC5D)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP'],
        "groups": [],
    },
    'tarlatamab': {
        "name": 'Tarlatamab (Imdelltra)',
        "drug_class": 'Bispecific T-cell engager (target CD3 x DLL3)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP'],
        "groups": [],
    },
    'tebentafusp': {
        "name": 'Tebentafusp (Kimmtrak)',
        "drug_class": 'Bispecific T-cell engager (target TCR x gp100 (immune redirection))',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV', 'CMV', 'PJP'],
        "groups": [],
    },
    'daratumumab': {
        "name": 'Daratumumab (Darzalex / Darzalex Faspro)',
        "drug_class": 'Monoclonal antibody (anti-CD38)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'PJP'],
        "groups": [],
    },
    'isatuximab': {
        "name": 'Isatuximab (Sarclisa)',
        "drug_class": 'Monoclonal antibody (anti-CD38)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'PJP'],
        "groups": [],
    },
    'obinutuzumab': {
        "name": 'Obinutuzumab (Gazyva / Gazyvaro)',
        "drug_class": 'Monoclonal antibody (anti-CD20)',
        "risk_tags": ['HBV reactivation', 'Encapsulated bacteria', 'Bacterial (general)', 'VZV/HSV', 'PJP'],
        "groups": [],
    },
    'tafasitamab': {
        "name": 'Tafasitamab (Monjuvi / Minjuvi)',
        "drug_class": 'Monoclonal antibody (B-cell directed)',
        "risk_tags": ['Encapsulated bacteria', 'Bacterial (general)', 'VZV/HSV', 'HBV reactivation'],
        "groups": [],
    },
    'ocrelizumab': {
        "name": 'Ocrelizumab (Ocrevus)',
        "drug_class": 'Monoclonal antibody (anti-CD20)',
        "risk_tags": ['HBV reactivation', 'Encapsulated bacteria', 'Bacterial (general)', 'VZV/HSV'],
        "groups": [],
    },
    'ublituximab': {
        "name": 'Ublituximab (Briumvi)',
        "drug_class": 'Monoclonal antibody (anti-CD20)',
        "risk_tags": ['HBV reactivation', 'Encapsulated bacteria', 'Bacterial (general)', 'VZV/HSV'],
        "groups": [],
    },
    'ofatumumab_kesimpta': {
        "name": 'Ofatumumab (Kesimpta)',
        "drug_class": 'Monoclonal antibody (anti-CD20)',
        "risk_tags": ['HBV reactivation', 'Encapsulated bacteria', 'Bacterial (general)', 'VZV/HSV'],
        "groups": [],
    },
    'ado_trastuzumab_emtansine': {
        "name": 'Ado-trastuzumab emtansine (Kadcyla)',
        "drug_class": 'Antibody-drug conjugate (ADC; target HER2)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'trastuzumab_deruxtecan': {
        "name": 'Fam-trastuzumab deruxtecan (Enhertu)',
        "drug_class": 'Antibody-drug conjugate (ADC; target HER2)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'brentuximab_vedotin': {
        "name": 'Brentuximab vedotin (Adcetris)',
        "drug_class": 'Antibody-drug conjugate (ADC; target CD30)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'polatuzumab_vedotin': {
        "name": 'Polatuzumab vedotin (Polivy)',
        "drug_class": 'Antibody-drug conjugate (ADC; target CD79b)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'enfortumab_vedotin': {
        "name": 'Enfortumab vedotin (Padcev)',
        "drug_class": 'Antibody-drug conjugate (ADC; target Nectin-4)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'sacituzumab_govitecan': {
        "name": 'Sacituzumab govitecan (Trodelvy)',
        "drug_class": 'Antibody-drug conjugate (ADC; target Trop-2)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'mirvetuximab_soravtansine': {
        "name": 'Mirvetuximab soravtansine (Elahere)',
        "drug_class": 'Antibody-drug conjugate (ADC; target FRalpha)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'tisotumab_vedotin': {
        "name": 'Tisotumab vedotin (Tivdak)',
        "drug_class": 'Antibody-drug conjugate (ADC; target Tissue factor)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'belantamab_mafodotin': {
        "name": 'Belantamab mafodotin (Blenrep)',
        "drug_class": 'Antibody-drug conjugate (ADC; target BCMA)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'loncastuximab_tesirine': {
        "name": 'Loncastuximab tesirine (Zynlonta)',
        "drug_class": 'Antibody-drug conjugate (ADC; target CD19)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'gemtuzumab_ozogamicin': {
        "name": 'Gemtuzumab ozogamicin (Mylotarg)',
        "drug_class": 'Antibody-drug conjugate (ADC; target CD33)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'inotuzumab_ozogamicin': {
        "name": 'Inotuzumab ozogamicin (Besponsa)',
        "drug_class": 'Antibody-drug conjugate (ADC; target CD22)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'tagraxofusp': {
        "name": 'Tagraxofusp (Elzonris)',
        "drug_class": 'Antibody-drug conjugate (ADC; target CD123)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'C. difficile', 'PJP'],
        "groups": [],
    },
    'amivantamab': {
        "name": 'Amivantamab (Rybrevant)',
        "drug_class": 'Monoclonal antibody (EGFR/MET bispecific)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'daratumumab_faspro': {
        "name": 'Daratumumab + hyaluronidase (Darzalex Faspro)',
        "drug_class": 'Monoclonal antibody (anti-CD38 formulation)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'PJP'],
        "groups": [],
    },
    'dinutuximab': {
        "name": 'Dinutuximab (Unituxin)',
        "drug_class": 'Monoclonal antibody (anti-GD2)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'dinutuximab_beta': {
        "name": 'Dinutuximab beta (Qarziba)',
        "drug_class": 'Monoclonal antibody (anti-GD2)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'elotuzumab': {
        "name": 'Elotuzumab (Empliciti)',
        "drug_class": 'Monoclonal antibody (SLAMF7; myeloma)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'PJP'],
        "groups": [],
    },
    'mogamulizumab': {
        "name": 'Mogamulizumab (Poteligeo)',
        "drug_class": 'Monoclonal antibody (CCR4)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV', 'CMV'],
        "groups": [],
    },
    'siltuximab': {
        "name": 'Siltuximab (Sylvant)',
        "drug_class": 'Monoclonal antibody (anti-IL-6)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'aldesleukin': {
        "name": 'Aldesleukin (Proleukin)',
        "drug_class": 'Immune-stimulating cytokine / immunotherapy',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'nogapendekin': {
        "name": 'Nogapendekin alfa (Anktiva)',
        "drug_class": 'Immune-stimulating cytokine / immunotherapy',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    't_vecc': {
        "name": 'Talimogene laherparepvec (Imlygic)',
        "drug_class": 'Oncolytic virus therapy',
        "risk_tags": ['VZV/HSV', 'Bacterial (general)'],
        "groups": [],
    },
    'nadofaragene': {
        "name": 'Nadofaragene firadenovec (Adstiladrin)',
        "drug_class": 'Gene therapy (local administration)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'bevacizumab': {
        "name": 'Bevacizumab (Avastin)',
        "drug_class": 'Monoclonal antibody / fusion protein (VEGF/angiogenesis pathway)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'bevacizumab_awwb': {
        "name": 'Bevacizumab-awwb (Mvasi)',
        "drug_class": 'Monoclonal antibody / fusion protein (VEGF/angiogenesis pathway)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'bevacizumab_bvzr': {
        "name": 'Bevacizumab-bvzr (Zirabev)',
        "drug_class": 'Monoclonal antibody / fusion protein (VEGF/angiogenesis pathway)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'ramucirumab': {
        "name": 'Ramucirumab (Cyramza)',
        "drug_class": 'Monoclonal antibody / fusion protein (VEGF/angiogenesis pathway)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'ziv_aflibercept': {
        "name": 'ziv-Aflibercept (Zaltrap)',
        "drug_class": 'Monoclonal antibody / fusion protein (VEGF/angiogenesis pathway)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'cetuximab': {
        "name": 'Cetuximab (Erbitux)',
        "drug_class": 'Monoclonal antibody (EGFR pathway)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'panitumumab': {
        "name": 'Panitumumab (Vectibix)',
        "drug_class": 'Monoclonal antibody (EGFR pathway)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'necitumumab': {
        "name": 'Necitumumab (Portrazza)',
        "drug_class": 'Monoclonal antibody (EGFR pathway)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'trastuzumab_herceptin': {
        "name": 'Trastuzumab (Herceptin)',
        "drug_class": 'Monoclonal antibody (HER2)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'trastuzumab_hylecta': {
        "name": 'Trastuzumab + hyaluronidase (Herceptin Hylecta)',
        "drug_class": 'Monoclonal antibody (HER2 formulation)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'trastuzumab_kanjinti': {
        "name": 'Trastuzumab (Kanjinti)',
        "drug_class": 'Monoclonal antibody (HER2)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'trastuzumab_ogivri': {
        "name": 'Trastuzumab (Ogivri)',
        "drug_class": 'Monoclonal antibody (HER2)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'trastuzumab_ontruzant': {
        "name": 'Trastuzumab (Ontruzant)',
        "drug_class": 'Monoclonal antibody (HER2)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'trastuzumab_herzuma': {
        "name": 'Trastuzumab (Herzuma)',
        "drug_class": 'Monoclonal antibody (HER2)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'trastuzumab_trazimera': {
        "name": 'Trastuzumab (Trazimera)',
        "drug_class": 'Monoclonal antibody (HER2)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'trastuzumab_zercepac': {
        "name": 'Trastuzumab (Zercepac)',
        "drug_class": 'Monoclonal antibody (HER2)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'pertuzumab': {
        "name": 'Pertuzumab (Perjeta)',
        "drug_class": 'Monoclonal antibody (HER2 dimerization inhibitor)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'phesgo': {
        "name": 'Pertuzumab + trastuzumab + hyaluronidase (Phesgo)',
        "drug_class": 'Monoclonal antibody combo (HER2)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'margetuximab': {
        "name": 'Margetuximab (Margenza)',
        "drug_class": 'Monoclonal antibody (HER2)',
        "risk_tags": ['Bacterial (general)'],
        "groups": [],
    },
    'alemtuzumab': {
        "name": 'Alemtuzumab (Campath)',
        "drug_class": 'Monoclonal antibody (anti-CD52)',
        "risk_tags": ['CMV', 'PJP', 'VZV/HSV', 'Bacterial (general)', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'idelalisib': {
        "name": 'Idelalisib (Zydelig)',
        "drug_class": 'Targeted therapy (PI3Kδ inhibitor)',
        "risk_tags": ['PJP', 'CMV', 'Bacterial (general)', 'VZV/HSV'],
        "groups": [],
    },
    'duvelisib': {
        "name": 'Duvelisib (Copiktra)',
        "drug_class": 'Targeted therapy (PI3Kδ/gamma inhibitor)',
        "risk_tags": ['PJP', 'CMV', 'Bacterial (general)', 'VZV/HSV'],
        "groups": [],
    },
    'venetoclax': {
        "name": 'Venetoclax (Venclexta)',
        "drug_class": 'Targeted therapy (BCL-2 inhibitor)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)', 'PJP'],
        "groups": [],
    },
    'imatinib': {
        "name": 'Imatinib',
        "drug_class": 'Targeted therapy (BCR-ABL TKI)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)'],
        "groups": [],
    },
    'dasatinib': {
        "name": 'Dasatinib',
        "drug_class": 'Targeted therapy (BCR-ABL TKI)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'VZV/HSV'],
        "groups": [],
    },
    'nilotinib': {
        "name": 'Nilotinib',
        "drug_class": 'Targeted therapy (BCR-ABL TKI)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)'],
        "groups": [],
    },
    'bosutinib': {
        "name": 'Bosutinib',
        "drug_class": 'Targeted therapy (BCR-ABL TKI)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)'],
        "groups": [],
    },
    'ponatinib': {
        "name": 'Ponatinib',
        "drug_class": 'Targeted therapy (BCR-ABL TKI)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)'],
        "groups": [],
    },
    'selinexor': {
        "name": 'Selinexor',
        "drug_class": 'Targeted therapy (XPO1 inhibitor)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'VZV/HSV', 'PJP'],
        "groups": [],
    },
    'bortezomib': {
        "name": 'Bortezomib',
        "drug_class": 'Targeted therapy (proteasome inhibitor)',
        "risk_tags": ['VZV/HSV', 'Bacterial (general)', 'PJP'],
        "groups": [],
    },
    'carfilzomib': {
        "name": 'Carfilzomib',
        "drug_class": 'Targeted therapy (proteasome inhibitor)',
        "risk_tags": ['VZV/HSV', 'Bacterial (general)', 'PJP'],
        "groups": [],
    },
    'ixazomib': {
        "name": 'Ixazomib',
        "drug_class": 'Targeted therapy (proteasome inhibitor)',
        "risk_tags": ['VZV/HSV', 'Bacterial (general)', 'PJP'],
        "groups": [],
    },
    'thalidomide': {
        "name": 'Thalidomide',
        "drug_class": 'Targeted therapy (IMiD)',
        "risk_tags": ['Bacterial (general)', 'VZV/HSV'],
        "groups": [],
    },
    'lenalidomide': {
        "name": 'Lenalidomide',
        "drug_class": 'Targeted therapy (IMiD)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV'],
        "groups": [],
    },
    'pomalidomide': {
        "name": 'Pomalidomide',
        "drug_class": 'Targeted therapy (IMiD)',
        "risk_tags": ['Bacterial (general)', 'Neutropenia-related infections', 'VZV/HSV'],
        "groups": [],
    },
    'midostaurin': {
        "name": 'Midostaurin',
        "drug_class": 'Targeted therapy (FLT3 inhibitor)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'gilteritinib': {
        "name": 'Gilteritinib',
        "drug_class": 'Targeted therapy (FLT3 inhibitor)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'quizartinib': {
        "name": 'Quizartinib',
        "drug_class": 'Targeted therapy (FLT3 inhibitor)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'ivosidenib': {
        "name": 'Ivosidenib',
        "drug_class": 'Targeted therapy (IDH1 inhibitor)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)'],
        "groups": [],
    },
    'enasidenib': {
        "name": 'Enasidenib',
        "drug_class": 'Targeted therapy (IDH2 inhibitor)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)'],
        "groups": [],
    },
    'fludarabine': {
        "name": 'Fludarabine',
        "drug_class": 'Antimetabolite (purine analog)',
        "risk_tags": ['PJP', 'VZV/HSV', 'CMV', 'Bacterial (general)', 'Neutropenia-related infections', 'Invasive mold (Aspergillus)'],
        "groups": ['pjp_high_risk'],
    },
    'cladribine': {
        "name": 'Cladribine',
        "drug_class": 'Antimetabolite (purine analog)',
        "risk_tags": ['PJP', 'VZV/HSV', 'CMV', 'Bacterial (general)', 'Neutropenia-related infections', 'Invasive mold (Aspergillus)'],
        "groups": ['pjp_high_risk'],
    },
    'pentostatin': {
        "name": 'Pentostatin',
        "drug_class": 'Antimetabolite (purine analog)',
        "risk_tags": ['PJP', 'VZV/HSV', 'CMV', 'Bacterial (general)', 'Neutropenia-related infections', 'Invasive mold (Aspergillus)'],
        "groups": ['pjp_high_risk'],
    },
    'ofatumumab': {
        "name": 'Ofatumumab (Arzerra)',
        "drug_class": 'Monoclonal antibody (anti-CD20)',
        "risk_tags": ['HBV reactivation', 'Encapsulated bacteria', 'Bacterial (general)', 'VZV/HSV', 'PJP'],
        "groups": [],
    },
    'azacitidine': {
        "name": 'Azacitidine (Onureg)',
        "drug_class": 'Hypomethylating agent',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'decitabine': {
        "name": 'Decitabine',
        "drug_class": 'Hypomethylating agent',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'Invasive mold (Aspergillus)'],
        "groups": [],
    },
    'nelarabine': {
        "name": 'Nelarabine (Arranon)',
        "drug_class": 'Antimetabolite',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile', 'Invasive mold (Aspergillus)', 'PJP'],
        "groups": ['cytotoxic_chemo'],
    },
    'clofarabine': {
        "name": 'Clofarabine (Clolar)',
        "drug_class": 'Antimetabolite',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile', 'Invasive mold (Aspergillus)', 'PJP'],
        "groups": ['cytotoxic_chemo'],
    },
    'pegaspargase': {
        "name": 'Pegaspargase (Oncaspar)',
        "drug_class": 'Enzyme therapy (asparaginase)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile'],
        "groups": [],
    },
    'calaspargase': {
        "name": 'Calaspargase pegol (Asparlas)',
        "drug_class": 'Enzyme therapy (asparaginase)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)', 'C. difficile'],
        "groups": [],
    },
    'erwinia_asparaginase': {
        "name": 'Asparaginase Erwinia chrysanthemi (Erwinaze)',
        "drug_class": 'Enzyme therapy (asparaginase)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)'],
        "groups": [],
    },
    'rylaze': {
        "name": 'Asparaginase Erwinia chrysanthemi (recombinant) (Rylaze)',
        "drug_class": 'Enzyme therapy (asparaginase)',
        "risk_tags": ['Neutropenia-related infections', 'Bacterial (general)'],
        "groups": [],
    },
}
